version: "3"
services:
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    env_file: config.env
    image: spacious-db
    expose:
      - 5432
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      start_period: 10s
      timeout: 4s
      retries: 3
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    image: spacious-api
    ports:
      - 3000:5000
    volumes:
      - /app/node_modules
      - ./server:/my-app
    env_file: config.env
    networks:
      - backend
      - frontend
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: spacious-client
    ports:
      - 4003:4002
    volumes:
      - /app/node_modules
      - ./client:/my-app
    networks:
      - frontend
networks:
  backend:
  frontend:
